#!/usr/bin/bash
# challenge of factors

factor_check()
{
	if [ $# -ne 3 ];
        then
                args=("$@")
                cnt=0
                num2=1
                for a in ${args[*]};
                do
                        if [ $cnt -gt 1 ];
                        then
                                num2=$(echo $a*$num2 | bc)
                        fi
                        cnt=$((cnt + 1))
                done
        else
                num2=$3
        fi

        num1=$2
        num=$(echo "$1" | tr ':' '=')

        reslt=$(echo "if($num2 > $num1) 1 else 0" | bc)
	        if ((reslt == 1)); then
		        numcp=$num1
		        num1=$num2
		        num2=$numcp
                fi

        echo "$num$num1*$num2"
}

if [ $# -ne 1 ]
then
        echo 'Usage: factors <file>'
        exit 1
else

        while read i
        do

                reslt=$(factor "$i")
                check_factor $reslt

        done < "$1"
fi
